name: Build Strategies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1-5'

jobs:
  build-strategies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install dependencies with pipenv
        run: |
          pipx install pipenv
          pipenv install --deploy --dev
      - name: Check opening days
        id: check-opening-day
        run: |
          pipenv run python -c "from trader.openday import is_opening; print(is_opening())"
      - name: Build strategies
        if: steps.check-opening-day.outputs.stdout == 'True'
        run: |
          echo "Building strategies..."
