name: Build Strategies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1-5'

jobs:
  build-strategies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Setup Python3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies with poetry
        run: |
          poetry install
      - name: Check opening days
        id: check-opening-day
        run: |
          echo "OPEN_DAY="$(poetry run python -c "from trader.openday import is_opening; print(is_opening())") >> $GITHUB_OUTPUT
      - name: Build strategies
        if: ${{steps.check-opening-day.outputs.OPEN_DAY == 'True'}}
        run: poetry run python run_strategies.py
